// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * Copyright (C) 2019 CAMELab
 *
 * Author: Donghyun Gouk <kukdh1@camelab.org>
 */

#include "src/insts/arm/cortex_r52.hh"

#include <iostream>

namespace Instruction::ARM {

RuleList rule_r52 = {
    {'A', {"ADCS?", Type::Arithmetic, 1}},
    {'A', {"ADDS?", Type::Arithmetic, 1}},
    {'A', {"ADR", Type::Arithmetic, 1}},
    {'A', {"ANDS?", Type::Arithmetic, 1}},
    {'A', {"ASRS?", Type::Arithmetic, 1}},
    {'B',
     {"B(EQ|NE|CS|HS|CC|LO|MI|PL|VS|VC|HI|LS|GE|LT|GT|LE|AL|NV)?", Type::Branch,
      1}},
    {'B', {"BFC", Type::Arithmetic, 1}},
    {'B', {"BFI", Type::Arithmetic, 1}},
    {'B', {"BICS?", Type::Arithmetic, 1}},
    {'B', {"BKPT", Type::Other, 1}},
    {'B', {"BL", Type::Branch, 1}},
    {'B', {"BLX", Type::Branch, 1}},
    {'B', {"BX", Type::Branch, 1}},
    {'B', {"BXJ", Type::Branch, 1}},
    {'C', {"CBN?Z", Type::Arithmetic, 1}},
    {'C', {"CLREX", Type::Other, 1}},
    {'C', {"CLZ", Type::Arithmetic, 1}},
    {'C', {"CMN", Type::Arithmetic, 1}},
    {'C', {"CMP", Type::Arithmetic, 1}},
    {'C', {"CPS(IE|ID)?", Type::Other, 1}},
    {'C', {"CRC32C?", Type::Arithmetic, 1}},
    {'D', {"DBG", Type::Other, 1}},
    {'D', {"DMB", Type::Other, 1}},
    {'D', {"DSB", Type::Other, 1}},
    {'E', {"EORS?", Type::Arithmetic, 1}},
    {'E', {"ERET", Type::Other, 1}},
    {'H', {"HLT", Type::Other, 1}},
    {'H', {"HVC", Type::Other, 1}},
    {'I', {"ISB", Type::Other, 1}},
    {'I', {"IT", Type::Branch, 1}},
    {'L', {"LDAB?", Type::Load, 1}},
    {'L', {"LDAEX(B|D|H)?", Type::Load, 1}},
    {'L', {"LDAH", Type::Load, 1}},
    {'L', {"LDC", Type::Load, 1}},
    {'L', {"LDM", Type::Load, 1}},
    {'L', {"LDM(D|I|F|E)(A|B|D)", Type::Load, 1}},
    {'L', {"LDRB?", Type::Load, 1}},
    {'L', {"LDRBT", Type::Load, 1}},
    {'L', {"LDRD", Type::Load, 1}},
    {'L', {"LDREX(B|D|H)?", Type::Load, 1}},
    {'L', {"LDRHT?", Type::Load, 1}},
    {'L', {"LDRSBT?", Type::Load, 1}},
    {'L', {"LDRSHT?", Type::Load, 1}},
    {'L', {"LDRT", Type::Load, 1}},
    {'L', {"LSLS?", Type::Arithmetic, 1}},
    {'L', {"LSRS?", Type::Arithmetic, 1}},
    {'M', {"MCRR?", Type::Other, 1}},
    {'M', {"MLAS?", Type::Arithmetic, 1}},
    {'M', {"MLS", Type::Arithmetic, 1}},
    {'M', {"MOVS?", Type::Arithmetic, 1}},
    {'M', {"MOVT", Type::Arithmetic, 1}},
    {'M', {"MRC", Type::Other, 1}},
    {'M', {"MRRC", Type::Other, 1}},
    {'M', {"MRS", Type::Other, 1}},
    {'M', {"MSR", Type::Other, 1}},
    {'M', {"MULS?", Type::Arithmetic, 1}},
    {'M', {"MVNS?", Type::Arithmetic, 1}},
    {'N', {"NOP", Type::Other, 1}},
    {'O', {"ORNS?", Type::Arithmetic, 1}},
    {'O', {"ORRS?", Type::Arithmetic, 1}},
    {'P', {"PKHBT", Type::Arithmetic, 1}},
    {'P', {"PLD(B|W)?", Type::Other, 1}},
    {'P', {"POP", Type::Other, 1}},
    {'P', {"PUSH", Type::Other, 1}},
    {'Q', {"QADD", Type::Arithmetic, 1}},
    {'Q', {"QADD16", Type::Arithmetic, 1}},
    {'Q', {"QADD8", Type::Arithmetic, 1}},
    {'Q', {"QASX", Type::Arithmetic, 1}},
    {'Q', {"QDADD", Type::Arithmetic, 1}},
    {'Q', {"QDSUB", Type::Arithmetic, 1}},
    {'Q', {"QSAX", Type::Arithmetic, 1}},
    {'Q', {"QSUB", Type::Arithmetic, 1}},
    {'Q', {"QSUB16", Type::Arithmetic, 1}},
    {'Q', {"QSUB8", Type::Arithmetic, 1}},
    {'R', {"RBIT", Type::Arithmetic, 1}},
    {'R', {"REV", Type::Arithmetic, 1}},
    {'R', {"REV16", Type::Arithmetic, 1}},
    {'R', {"REVSH", Type::Arithmetic, 1}},
    {'R', {"RFE(DA|DB|IA|IB)?", Type::Other, 1}},
    {'R', {"RORS?", Type::Arithmetic, 1}},
    {'R', {"RRXS?", Type::Arithmetic, 1}},
    {'R', {"RSBS?", Type::Arithmetic, 1}},
    {'R', {"RSCS?", Type::Arithmetic, 1}},
    {'S', {"SADD16", Type::Arithmetic, 1}},
    {'S', {"SADD8", Type::Arithmetic, 1}},
    {'S', {"SASX", Type::Arithmetic, 1}},
    {'S', {"SBCS?", Type::Arithmetic, 1}},
    {'S', {"SBFX", Type::Arithmetic, 1}},
    {'S', {"SDIV", Type::Arithmetic, 1}},
    {'S', {"SEL", Type::Arithmetic, 1}},
    {'S', {"SELEND", Type::Arithmetic, 1}},
    {'S', {"SEVL?", Type::Other, 1}},
    {'S', {"SHADD16", Type::Arithmetic, 1}},
    {'S', {"SHADD8", Type::Arithmetic, 1}},
    {'S', {"SHASX", Type::Arithmetic, 1}},
    {'S', {"SHSAX", Type::Arithmetic, 1}},
    {'S', {"SHSUB16", Type::Arithmetic, 1}},
    {'S', {"SHSUB8", Type::Arithmetic, 1}},
    {'S', {"SMLA(BB|BT|TB|TT)", Type::Arithmetic, 1}},
    {'S', {"SMLADX?", Type::Arithmetic, 1}},
    {'S', {"SMLAL(BB|BT|TB|TT)", Type::Arithmetic, 1}},
    {'S', {"SMLALDX?", Type::Arithmetic, 1}},
    {'S', {"SMLALS?", Type::Arithmetic, 1}},
    {'S', {"SMLAW(B|T)", Type::Arithmetic, 1}},
    {'S', {"SMLSDX?", Type::Arithmetic, 1}},
    {'S', {"SMLSLDX?", Type::Arithmetic, 1}},
    {'S', {"SMMLAR?", Type::Arithmetic, 1}},
    {'S', {"SMMLSR?", Type::Arithmetic, 1}},
    {'S', {"SMMULR?", Type::Arithmetic, 1}},
    {'S', {"SMUADX?", Type::Arithmetic, 1}},
    {'S', {"SMUL(BB|BT|TB|TT)", Type::Arithmetic, 1}},
    {'S', {"SMULLS?", Type::Arithmetic, 1}},
    {'S', {"SMULW(B|T)", Type::Arithmetic, 1}},
    {'S', {"SMUSDX?", Type::Arithmetic, 1}},
    {'S', {"SRS(DA|DB|IA|IB)?", Type::Other, 1}},
    {'S', {"SSAT", Type::Arithmetic, 1}},
    {'S', {"SSAT16", Type::Arithmetic, 1}},
    {'S', {"SSAX", Type::Arithmetic, 1}},
    {'S', {"SSUB16", Type::Arithmetic, 1}},
    {'S', {"SSUB8", Type::Arithmetic, 1}},
    {'S', {"STC", Type::Other, 1}},
    {'S', {"STLB?", Type::Other, 2}},
    {'S', {"STLEX(B|D|H)?", Type::Other, 2}},
    {'S', {"STLH", Type::Other, 2}},
    {'S', {"STM(DA|ED|DB|FD|IB|FA)", Type::Store, 1}},
    {'S', {"STM(IA|EA)?", Type::Store, 1}},
    {'S', {"STRB?", Type::Store, 1}},
    {'S', {"STRBT", Type::Store, 1}},
    {'S', {"STRD", Type::Store, 1}},
    {'S', {"STREX(B|D|H)?", Type::Store, 1}},
    {'S', {"STRHT?", Type::Store, 1}},
    {'S', {"STRT", Type::Store, 1}},
    {'S', {"SUBS?", Type::Arithmetic, 1}},
    {'S', {"SVC", Type::Other, 1}},
    {'S', {"SXTAB", Type::Arithmetic, 1}},
    {'S', {"SXTAB16", Type::Arithmetic, 1}},
    {'S', {"SXTAH", Type::Arithmetic, 1}},
    {'S', {"SXTB", Type::Arithmetic, 1}},
    {'S', {"SXTB16", Type::Arithmetic, 1}},
    {'S', {"SXTH", Type::Arithmetic, 1}},
    {'T', {"TBB", Type::Branch, 1}},
    {'T', {"TBH", Type::Branch, 1}},
    {'T', {"TEQ", Type::Arithmetic, 1}},
    {'T', {"TST", Type::Arithmetic, 1}},
    {'U', {"UADD16", Type::Arithmetic, 1}},
    {'U', {"UADD8", Type::Arithmetic, 1}},
    {'U', {"UASX", Type::Arithmetic, 1}},
    {'U', {"UBFX", Type::Arithmetic, 1}},
    {'U', {"UDIV", Type::Arithmetic, 1}},
    {'U', {"UHADD16", Type::Arithmetic, 1}},
    {'U', {"UHADD9", Type::Arithmetic, 1}},
    {'U', {"UHASX", Type::Arithmetic, 1}},
    {'U', {"UHSAX", Type::Arithmetic, 1}},
    {'U', {"UHSUB16", Type::Arithmetic, 1}},
    {'U', {"UHSUB8", Type::Arithmetic, 1}},
    {'U', {"UMAAL", Type::Arithmetic, 2}},
    {'U', {"UMLALS?", Type::Arithmetic, 1}},
    {'U', {"UMULLS?", Type::Arithmetic, 1}},
    {'U', {"UQADD16", Type::Arithmetic, 1}},
    {'U', {"UQADD8", Type::Arithmetic, 1}},
    {'U', {"USAD8", Type::Arithmetic, 1}},
    {'U', {"USADA8", Type::Arithmetic, 1}},
    {'U', {"USAT", Type::Arithmetic, 1}},
    {'U', {"USAT16", Type::Arithmetic, 1}},
    {'U', {"USUB8", Type::Arithmetic, 1}},
    {'U', {"UXTAB", Type::Arithmetic, 1}},
    {'U', {"UXTAB16", Type::Arithmetic, 1}},
    {'U', {"UXTAH", Type::Arithmetic, 1}},
    {'U', {"UXTB", Type::Arithmetic, 1}},
    {'U', {"UXTB16", Type::Arithmetic, 1}},
    {'U', {"UXTH", Type::Arithmetic, 1}},
    {'V', {"VABAL?", Type::Other, 2}},
    {'V', {"VABDL?", Type::Other, 1}},
    {'V', {"VABS", Type::Other, 1}},
    {'V', {"VACG(E|T)", Type::Other, 1}},
    {'V', {"VADD", Type::Other, 1}},
    {'V', {"VADDHN", Type::Other, 1}},
    {'V', {"VADDL", Type::Other, 1}},
    {'V', {"VADDW", Type::Other, 1}},
    {'V', {"VAND", Type::Other, 1}},
    {'V', {"VBI(C|F|T)", Type::Other, 1}},
    {'V', {"VBSL", Type::Other, 1}},
    {'V', {"VC(EQ|GE|GT|LE|LS|LT|LZ|MP|MPE|NT)", Type::Other, 1}},
    {'V', {"VCVT(A|B|M|N|P|R|T)?", Type::Other, 1}},
    {'V', {"VDIV", Type::Other, 1}},
    {'V', {"VDUP", Type::Other, 1}},
    {'V', {"VEOR", Type::Other, 1}},
    {'V', {"VEXT", Type::Other, 1}},
    {'V', {"VFMA", Type::Other, 1}},
    {'V', {"VFMS", Type::Other, 1}},
    {'V', {"VFNMA", Type::Other, 1}},
    {'V', {"VFNMS", Type::Other, 1}},
    {'V', {"VHADD", Type::Other, 1}},
    {'V', {"VHSUB", Type::Other, 1}},
    {'V', {"VLD1", Type::Load, 1}},
    {'V', {"VLD2", Type::Load, 2}},
    {'V', {"VLD3", Type::Load, 3}},
    {'V', {"VLD4", Type::Load, 4}},
    {'V', {"VLDM(DB|IA)?", Type::Load, 1}},
    {'V', {"VLDR", Type::Load, 1}},
    {'V', {"VMAX(NM)?", Type::Other, 1}},
    {'V', {"VMIN(NM)?", Type::Other, 1}},
    {'V', {"VMLAL?", Type::Other, 1}},
    {'V', {"VMLSL?", Type::Other, 1}},
    {'V', {"VMOV(L|N)?", Type::Other, 1}},
    {'V', {"VMRS", Type::Other, 1}},
    {'V', {"VMSR", Type::Other, 1}},
    {'V', {"VMULL?", Type::Other, 1}},
    {'V', {"VMVN", Type::Other, 1}},
    {'V', {"VNEG", Type::Other, 1}},
    {'V', {"VNML(A|S)", Type::Other, 1}},
    {'V', {"VNMUL", Type::Other, 1}},
    {'V', {"VOR(N|R)", Type::Other, 1}},
    {'V', {"VPADAL", Type::Other, 1}},
    {'V', {"VPADDL?", Type::Other, 1}},
    {'V', {"VPMAX", Type::Other, 1}},
    {'V', {"VPMIN", Type::Other, 1}},
    {'V', {"VPOP", Type::Other, 1}},
    {'V', {"VPUSH", Type::Other, 1}},
    {'V', {"VQABS", Type::Other, 1}},
    {'V', {"VQADD", Type::Other, 1}},
    {'V', {"VQDML(AL|SL)", Type::Other, 1}},
    {'V', {"VQDMU(LH|LL)", Type::Other, 1}},
    {'V', {"VQMOV(N|UN)", Type::Other, 1}},
    {'V', {"VQNEG", Type::Other, 1}},
    {'V', {"VQRDMULH", Type::Other, 1}},
    {'V', {"VQRSHL", Type::Other, 1}},
    {'V', {"VQRSHRU?N", Type::Other, 1}},
    {'V', {"VQSHLU?", Type::Other, 1}},
    {'V', {"VQSHRU?N", Type::Other, 1}},
    {'V', {"VQSUB", Type::Other, 1}},
    {'V', {"VRADDHN", Type::Other, 2}},
    {'V', {"VRECP(E|S)", Type::Other, 1}},
    {'V', {"VREV(16|32|64)", Type::Other, 1}},
    {'V', {"VRHADD", Type::Other, 1}},
    {'V', {"VRINT(A|M|N|P|R|X|Z)", Type::Other, 1}},
    {'V', {"VRSHL", Type::Other, 1}},
    {'V', {"VRSHRN?", Type::Other, 1}},
    {'V', {"VRSQRT(E|S)", Type::Other, 1}},
    {'V', {"VRSRA", Type::Other, 2}},
    {'V', {"VRSUBHN", Type::Other, 2}},
    {'V', {"VSEL(EQ|GE|GT|VS)", Type::Other, 1}},
    {'V', {"VSHLL?", Type::Other, 1}},
    {'V', {"VSHRN?", Type::Other, 1}},
    {'V', {"VSLI", Type::Other, 1}},
    {'V', {"VSQRT", Type::Other, 1}},
    {'V', {"VSRA", Type::Other, 1}},
    {'V', {"VSRI", Type::Other, 1}},
    {'V', {"VST1", Type::Store, 1}},
    {'V', {"VST2", Type::Store, 2}},
    {'V', {"VST3", Type::Store, 4}},
    {'V', {"VST4", Type::Store, 5}},
    {'V', {"VSTM(DB|IA)?", Type::Store, 1}},
    {'V', {"VSTR", Type::Store, 1}},
    {'V', {"VSUB", Type::Other, 1}},
    {'V', {"VSUB(L|W)?", Type::Other, 1}},
    {'V', {"VSUBHN", Type::Other, 1}},
    {'V', {"VSWP", Type::Other, 1}},
    {'V', {"VTBL", Type::Other, 1}},
    {'V', {"VTLX", Type::Other, 1}},
    {'V', {"VTRN", Type::Other, 2}},
    {'V', {"VTST", Type::Other, 1}},
    {'V', {"VUZP", Type::Other, 2}},
    {'V', {"VZIP", Type::Other, 1}},
    {'W', {"WFE", Type::Other, 5}},
    {'W', {"WFI", Type::Other, 5}},
    {'Y', {"YIELD", Type::Other, 1}},
    {'F', {"FMOV", Type::FloatingPoint, 5}},
    {'F', {"FCVT(XN|)", Type::FloatingPoint, 5}},
    {'F', {"FCVT(AS|AU|MS|MU|NS|NU|PS|PU|ZS|ZU)", Type::FloatingPoint, 10}},
    {'F', {"FJCVTZS", Type::FloatingPoint, 1}},
    {'S', {"SCVTF", Type::FloatingPoint, 10}},
    {'U', {"UCVTF", Type::FloatingPoint, 10}},
    {'F', {"FRINT(A|I|M|N|P|X|Z|)", Type::FloatingPoint, 5}},
    {'F', {"FMADD", Type::FloatingPoint, 9}},
    {'F', {"FMSUB", Type::FloatingPoint, 9}},
    {'F', {"FNMADD", Type::FloatingPoint, 9}},
    {'F', {"FNMSUB", Type::FloatingPoint, 9}},
    {'F', {"FABS", Type::FloatingPoint, 3}},
    {'F', {"FNEG", Type::FloatingPoint, 3}},
    {'F', {"FSQRT", Type::FloatingPoint, 20}},
    {'F', {"FADD", Type::FloatingPoint, 5}},
    {'F', {"FDIV", Type::FloatingPoint, 20}},
    {'F', {"FMUL", Type::FloatingPoint, 6}},
    {'F', {"FNMUL", Type::FloatingPoint, 6}},
    {'F', {"FSUB", Type::FloatingPoint, 5}},
    {'F', {"FMAX", Type::FloatingPoint, 5}},
    {'F', {"FMAXNM", Type::FloatingPoint, 5}},
    {'F', {"FMIN", Type::FloatingPoint, 5}},
    {'F', {"FMINNM", Type::FloatingPoint, 5}},
    {'F', {"FCMP(E|P|PE|)", Type::FloatingPoint, 3}},
    {'F', {"FCSEL", Type::FloatingPoint, 3}},
};

Type CortexR52::getStatistic(std::string &op, uint64_t &cycles) {
  char first = op.front();
  char other = first < 'a' ? first + ('a' - 'A') : first - ('a' - 'A');

  if (rule_r52.count(other) > 0) {
    first = other;
  }

  if (rule_r52.count(first) > 0) {
    auto range = rule_r52.equal_range(first);
    std::smatch match;

    for (auto iter = range.first; iter != range.second; ++iter) {
      if (std::regex_match(op, match, iter->second.regex)) {
        cycles = iter->second.cycle;

        return iter->second.type;
      }
    }
  }

  return Type::Ignore;
}

}  // namespace Instruction::ARM
